-- ============================================================
-- PROPOSED — not applied. Deliberately outside supabase/migrations/.
-- ============================================================
--
-- Move this file into supabase/migrations/ to apply it. It is parked here
-- because it changes row level security, and that is a decision for whoever
-- owns the database rather than something to slip into a feature branch.
--
-- ------------------------------------------------------------
-- Why this exists
-- ------------------------------------------------------------
-- The citizen mobile app ships the anon key inside its binary. That is normal
-- for Supabase — anon keys are public by design and RLS is what protects the
-- data — but it means every policy granted to `anon` is effectively granted to
-- anyone who downloads the app and runs `strings` on it.
--
-- 003_rls_policies.sql currently grants:
--
--   CREATE POLICY "alerts_insert" ON alerts FOR INSERT WITH CHECK (true);
--
-- So anyone holding the anon key can insert a row into `alerts` with severity
-- 'critical'. In this app a critical alert for the user's zone triggers a
-- full-screen takeover and vibration that cannot be dismissed by scrolling. A
-- public insert policy on that table is a public "make every phone in Kolkata
-- scream" endpoint.
--
-- The policy is not needed. generate_alert_from_reading() in
-- 004_alert_trigger.sql is SECURITY DEFINER, so its INSERT runs as the function
-- owner and bypasses RLS regardless of what `anon` may do. Alerts will keep
-- being generated from readings exactly as they are today.
--
-- The ESP32 firmware is unaffected: it posts to `readings`, and
-- "readings_insert" stays as it is.
--
-- ------------------------------------------------------------
-- What this changes
-- ------------------------------------------------------------
-- Removes the public insert path on alerts. Authorities issuing a manual alert
-- do so through an authenticated dashboard session or the service role, which is
-- what the alerts table comment in 002_tables.sql already anticipated
-- ("generated by trigger logic or manual entry").

DROP POLICY IF EXISTS "alerts_insert" ON alerts;

CREATE POLICY "alerts_insert_authenticated" ON alerts
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Readings stay publicly insertable so the field hardware keeps working with the
-- anon key. Worth revisiting separately: a forged reading above the flood
-- threshold still reaches the trigger and produces a real 'high' alert. Fixing
-- that properly means per-device credentials rather than a shared anon key, which
-- is a firmware change and not an RLS one.
