import type {
  Alert,
  AlertWithContext,
  Reading,
  RiskZone,
  RouteStep,
  SensorNode,
  Shelter,
  UserPosition,
} from '../domain/types';
import { distanceMetres } from '../domain/geo';

/**
 * Fixtures for the citizen app.
 *
 * The six sensor nodes are copied verbatim from supabase/migrations/
 * 005_seed_data.sql — same ids, same names, same coordinates — so that
 * screens built against these fixtures keep working when the Supabase client
 * is wired in and this file is deleted.
 *
 * Timestamps are relative to process start, mirroring the seed file's
 * `now() - interval '...'`, so "2 hours ago" stays true whenever the app runs.
 */

const T0 = Date.now();
const hoursAgo = (h: number) => new Date(T0 - h * 3_600_000).toISOString();
const minutesAgo = (m: number) => new Date(T0 - m * 60_000).toISOString();

export const NODES: SensorNode[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    name: 'Sundarbans Edge Alpha',
    node_type: 'forest',
    latitude: 22.512,
    longitude: 88.329,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    name: 'Salt Lake Sector V',
    node_type: 'urban',
    latitude: 22.5744,
    longitude: 88.4318,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    name: 'Howrah Bridge West',
    node_type: 'urban',
    latitude: 22.5851,
    longitude: 88.3468,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    name: 'Rabindra Sarobar Park',
    node_type: 'forest',
    latitude: 22.511,
    longitude: 88.359,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0005-4000-8000-000000000005',
    name: 'New Town Eco Park',
    node_type: 'universal',
    latitude: 22.6014,
    longitude: 88.4625,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    name: 'Jadavpur Campus',
    node_type: 'universal',
    latitude: 22.4966,
    longitude: 88.3712,
    status: 'active',
  },
];

const nodeById = (id: string): SensorNode => {
  const node = NODES.find((n) => n.id === id);
  if (!node) throw new Error(`Unknown node id in fixtures: ${id}`);
  return node;
};

/**
 * The user is in Ward 58, between Kalighat and Rabindra Sarobar — inside the
 * flood zone the seeded Howrah and Sarobar readings imply.
 */
export const USER_POSITION: UserPosition = {
  latitude: 22.5148,
  longitude: 88.361,
  accuracyMetres: 18,
  takenAt: minutesAgo(3),
  locality: 'Ward 58, Kolkata',
};

/**
 * The readings that tripped the alert trigger, taken from the seed file.
 * Shown on alert detail as evidence, so the warning is not a black box.
 */
export const TRIGGER_READINGS: Record<string, Reading> = {
  'alert-howrah-flood': {
    id: 'r-0003-2h',
    node_id: 'a1b2c3d4-0003-4000-8000-000000000003',
    temperature: 29.8,
    humidity: 82.0,
    flame_detected: false,
    smoke_level: 140,
    water_level: 3100,
    rain_level: 310,
    created_at: hoursAgo(2),
  },
  'alert-sarobar-fire': {
    id: 'r-0004-5h',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    temperature: 42.1,
    humidity: 65.0,
    flame_detected: true,
    smoke_level: 620,
    water_level: 400,
    rain_level: 20,
    created_at: hoursAgo(5),
  },
  'alert-sundarbans-flood': {
    id: 'r-0001-6h',
    node_id: 'a1b2c3d4-0001-4000-8000-000000000001',
    temperature: 28.9,
    humidity: 91.0,
    flame_detected: false,
    smoke_level: 75,
    water_level: 2100,
    rain_level: 350,
    created_at: hoursAgo(6),
  },
  'alert-ward58-critical': {
    id: 'r-0004-12m',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    temperature: 29.1,
    humidity: 94.0,
    flame_detected: false,
    smoke_level: 90,
    water_level: 3890,
    rain_level: 470,
    created_at: minutesAgo(12),
  },
};

/**
 * Three of these four are exactly the alerts 005_seed_data.sql inserts.
 *
 * The fourth (`alert-ward58-critical`) is severity 'critical', which the
 * current database trigger in 004_alert_trigger.sql never produces — its
 * highest output is 'high'. It is modelled here as an authority-issued alert,
 * which the schema explicitly allows ("generated by trigger logic or manual
 * entry"). Worth raising with the backend team: a citizen-facing app needs a
 * ceiling above 'high', otherwise "leave now" can never be expressed.
 */
const RAW_ALERTS: Alert[] = [
  {
    id: 'alert-ward58-critical',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    hazard_type: 'flood',
    severity: 'critical',
    message:
      'Water level 3890/4095 and rising. Ward 58 low-lying lanes are being evacuated.',
    resolved: false,
    created_at: minutesAgo(12),
  },
  {
    id: 'alert-howrah-flood',
    node_id: 'a1b2c3d4-0003-4000-8000-000000000003',
    hazard_type: 'flood',
    severity: 'high',
    message: 'Critical water level: 3100/4095 — possible flooding.',
    resolved: false,
    created_at: hoursAgo(2),
  },
  {
    id: 'alert-sarobar-fire',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    hazard_type: 'fire',
    severity: 'high',
    message: 'Fire detected at node. Temp: 42.1°C, flame sensor active.',
    resolved: false,
    created_at: hoursAgo(5),
  },
  {
    id: 'alert-sundarbans-flood',
    node_id: 'a1b2c3d4-0001-4000-8000-000000000001',
    hazard_type: 'flood',
    severity: 'medium',
    message: 'Elevated water level: 2100/4095 — monitor closely.',
    resolved: false,
    created_at: hoursAgo(6),
  },
];

/** Alerts joined to their node and to the user's distance from it. */
export const ALERTS: AlertWithContext[] = RAW_ALERTS.map((alert) => {
  const node = nodeById(alert.node_id);
  return {
    ...alert,
    node,
    distanceMetres: distanceMetres(USER_POSITION, node),
    trigger: TRIGGER_READINGS[alert.id] ?? null,
  };
});

/**
 * Real places in and around Ward 58. Elevation matters more than distance in a
 * Kolkata flood — the city is almost flat, so a metre of ground floor height is
 * the difference between a dry shelter and a wet one.
 */
export const SHELTERS: Shelter[] = [
  {
    id: 'shelter-deshapriya',
    name: 'Deshapriya Park Community Hall',
    address: 'Deshapriya Park East, off Rash Behari Avenue',
    latitude: 22.5175,
    longitude: 88.3585,
    capacity: 400,
    occupancy: 186,
    status: 'open',
    elevationMetres: 7.5,
    facilities: ['Drinking water', 'Toilets', 'Medical desk', 'Phone charging'],
  },
  {
    id: 'shelter-lake-gardens',
    name: 'Lake Gardens Govt. High School',
    address: 'Lake Gardens, near the railway crossing',
    latitude: 22.506,
    longitude: 88.356,
    capacity: 250,
    occupancy: 244,
    status: 'full',
    elevationMetres: 6.5,
    facilities: ['Drinking water', 'Toilets'],
  },
  {
    id: 'shelter-netaji-indoor',
    name: 'Netaji Indoor Stadium',
    address: 'Eden Gardens, Strand Road',
    latitude: 22.5636,
    longitude: 88.3395,
    capacity: 2000,
    occupancy: 410,
    status: 'open',
    elevationMetres: 6.0,
    facilities: [
      'Drinking water',
      'Toilets',
      'Medical desk',
      'Cooked meals',
      'Family rooms',
    ],
  },
  {
    id: 'shelter-jadavpur',
    name: 'Jadavpur Vidyapith',
    address: 'Bijoygarh, off Raja S C Mallick Road',
    latitude: 22.499,
    longitude: 88.3695,
    capacity: 300,
    occupancy: 92,
    status: 'open',
    elevationMetres: 8.2,
    facilities: ['Drinking water', 'Toilets', 'Cooked meals'],
  },
];

/**
 * Risk zones as [lng, lat] rings, matching PostGIS output order so a future
 * ST_AsGeoJSON response drops straight in.
 *
 * Kept to three coarse zones on purpose. The authority dashboard is where a
 * dense heatmap belongs; a citizen needs to know "am I in it or not".
 */
export const RISK_ZONES: RiskZone[] = [
  {
    id: 'zone-ward58',
    name: 'Ward 58 low-lying lanes',
    hazard: 'flood',
    severity: 'critical',
    polygon: [
      [88.3555, 22.5105],
      [88.3665, 22.5115],
      [88.3675, 22.5185],
      [88.3565, 22.5175],
    ],
  },
  {
    id: 'zone-hooghly-bank',
    name: 'Hooghly east bank',
    hazard: 'flood',
    severity: 'high',
    polygon: [
      [88.3405, 22.5745],
      [88.3515, 22.5765],
      [88.3535, 22.5925],
      [88.3425, 22.5905],
    ],
  },
  {
    id: 'zone-sarobar-scrub',
    name: 'Rabindra Sarobar dry scrub',
    hazard: 'fire',
    severity: 'high',
    polygon: [
      [88.3545, 22.5075],
      [88.3625, 22.5065],
      [88.3635, 22.5135],
      [88.3555, 22.5145],
    ],
  },
];

/**
 * Walking directions, keyed by shelter id.
 *
 * Deliberately a partial map, and partial in a specific way: the two shelters the
 * app can actually recommend from Ward 58 have steps, and the two it cannot —
 * Lake Gardens (full) and Netaji Indoor (5.9 km, beyond walking range) — do not.
 * That is the honest shape of routing data. A district will have surveyed walking
 * routes for the halls it evacuates people to and not for every building on the
 * list, so the app has to be able to say "I do not have turn-by-turn for this
 * one" rather than serving one shelter's streets under another's name.
 *
 * That failure mode is not hypothetical: an earlier version of the provider
 * returned Deshapriya Park's array for every destination, which would have walked
 * someone to the wrong building while sounding certain about it.
 *
 * Stubbed, as agreed — a real routing engine (OSRM or Mapbox Directions) fills
 * this shape. The streets are real, the manoeuvres are in the right order, the
 * leg distances sum to more than the straight-line distance because streets do,
 * and two legs carry cautions because a route that ignores the hazard it is
 * routing around is worse than no route.
 */
export const ROUTES: Record<string, RouteStep[]> = {
  'shelter-deshapriya': [
    {
      manoeuvre: 'start',
      instruction: 'Head north on Sadananda Road, away from the canal',
      distanceMetres: 120,
    },
    {
      manoeuvre: 'right',
      instruction: 'Turn right onto Rash Behari Avenue',
      distanceMetres: 260,
      caution: 'Water was knee-deep near the tram tracks 20 minutes ago',
    },
    {
      manoeuvre: 'left',
      instruction: 'Turn left onto Deshapriya Park East',
      distanceMetres: 90,
    },
    {
      manoeuvre: 'arrive',
      instruction: 'Shelter entrance is on your right, past the park gate',
      distanceMetres: 40,
    },
  ],
  /**
   * The recommended shelter for this position: 2.3 km on foot for 1.96 km of
   * straight line, which is the ordinary cost of following streets.
   *
   * The Prince Anwar Shah Road underpass caution is the most important line in
   * this file. Kolkata's rail underpasses fill first and drain last, and an
   * underpass is where a walk in a flood turns into a drowning. The route still
   * goes that way because it is the only continuous corridor south, so the step
   * says plainly what to do instead of it.
   */
  'shelter-jadavpur': [
    {
      manoeuvre: 'start',
      instruction: 'Head south on Sadananda Road towards Tollygunge',
      distanceMetres: 200,
    },
    {
      manoeuvre: 'left',
      instruction: 'Turn left onto Prince Anwar Shah Road',
      distanceMetres: 700,
      caution:
        'Do not enter the rail underpass if water is standing in it. Use the footbridge above it instead.',
    },
    {
      manoeuvre: 'right',
      instruction: 'Turn right onto Raja S C Mallick Road',
      distanceMetres: 900,
      caution: 'Stay on the raised footpath — the road edge holds water here',
    },
    {
      manoeuvre: 'left',
      instruction: 'Turn left into Bijoygarh, past the market',
      distanceMetres: 420,
    },
    {
      manoeuvre: 'arrive',
      instruction: 'Jadavpur Vidyapith gate is ahead on your left',
      distanceMetres: 90,
    },
  ],
};
