import type {
  Alert,
  AlertWithContext,
  Reading,
  RiskZone,
  SensorNode,
  Shelter,
  UserPosition,
} from '../domain/types';
import { distanceMetres } from '../domain/geo';

/**
 * Fixtures for the citizen app.
 *
 * The six sensor nodes are copied verbatim from supabase/migrations/
 * 005_seed_data.sql — same ids, same names, same coordinates — so that
 * screens built against these fixtures keep working when the Supabase client
 * is wired in and this file is deleted.
 *
 * Timestamps are relative to process start, mirroring the seed file's
 * `now() - interval '...'`, so "2 hours ago" stays true whenever the app runs.
 */

const T0 = Date.now();
const hoursAgo = (h: number) => new Date(T0 - h * 3_600_000).toISOString();
const minutesAgo = (m: number) => new Date(T0 - m * 60_000).toISOString();

export const NODES: SensorNode[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    name: 'Sundarbans Edge Alpha',
    node_type: 'forest',
    latitude: 22.512,
    longitude: 88.329,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    name: 'Salt Lake Sector V',
    node_type: 'urban',
    latitude: 22.5744,
    longitude: 88.4318,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    name: 'Howrah Bridge West',
    node_type: 'urban',
    latitude: 22.5851,
    longitude: 88.3468,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    name: 'Rabindra Sarobar Park',
    node_type: 'forest',
    latitude: 22.511,
    longitude: 88.359,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0005-4000-8000-000000000005',
    name: 'New Town Eco Park',
    node_type: 'universal',
    latitude: 22.6014,
    longitude: 88.4625,
    status: 'active',
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    name: 'Jadavpur Campus',
    node_type: 'universal',
    latitude: 22.4966,
    longitude: 88.3712,
    status: 'active',
  },
];

const nodeById = (id: string): SensorNode => {
  const node = NODES.find((n) => n.id === id);
  if (!node) throw new Error(`Unknown node id in fixtures: ${id}`);
  return node;
};

/**
 * The user is in Ward 58, between Kalighat and Rabindra Sarobar — inside the
 * flood zone the seeded Howrah and Sarobar readings imply.
 */
export const USER_POSITION: UserPosition = {
  latitude: 22.5148,
  longitude: 88.361,
  accuracyMetres: 18,
  takenAt: minutesAgo(3),
  locality: 'Ward 58, Kolkata',
};

/**
 * The readings that tripped the alert trigger, taken from the seed file.
 * Shown on alert detail as evidence, so the warning is not a black box.
 */
export const TRIGGER_READINGS: Record<string, Reading> = {
  'alert-howrah-flood': {
    id: 'r-0003-2h',
    node_id: 'a1b2c3d4-0003-4000-8000-000000000003',
    temperature: 29.8,
    humidity: 82.0,
    flame_detected: false,
    smoke_level: 140,
    water_level: 3100,
    rain_level: 310,
    created_at: hoursAgo(2),
  },
  'alert-sarobar-fire': {
    id: 'r-0004-5h',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    temperature: 42.1,
    humidity: 65.0,
    flame_detected: true,
    smoke_level: 620,
    water_level: 400,
    rain_level: 20,
    created_at: hoursAgo(5),
  },
  'alert-sundarbans-flood': {
    id: 'r-0001-6h',
    node_id: 'a1b2c3d4-0001-4000-8000-000000000001',
    temperature: 28.9,
    humidity: 91.0,
    flame_detected: false,
    smoke_level: 75,
    water_level: 2100,
    rain_level: 350,
    created_at: hoursAgo(6),
  },
  'alert-ward58-critical': {
    id: 'r-0004-12m',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    temperature: 29.1,
    humidity: 94.0,
    flame_detected: false,
    smoke_level: 90,
    water_level: 3890,
    rain_level: 470,
    created_at: minutesAgo(12),
  },
};

/**
 * Three of these four are exactly the alerts 005_seed_data.sql inserts.
 *
 * The fourth (`alert-ward58-critical`) is severity 'critical', which the
 * current database trigger in 004_alert_trigger.sql never produces — its
 * highest output is 'high'. It is modelled here as an authority-issued alert,
 * which the schema explicitly allows ("generated by trigger logic or manual
 * entry"). Worth raising with the backend team: a citizen-facing app needs a
 * ceiling above 'high', otherwise "leave now" can never be expressed.
 */
const RAW_ALERTS: Alert[] = [
  {
    id: 'alert-ward58-critical',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    hazard_type: 'flood',
    severity: 'critical',
    message:
      'Water level 3890/4095 and rising. Ward 58 low-lying lanes are being evacuated.',
    resolved: false,
    created_at: minutesAgo(12),
  },
  {
    id: 'alert-howrah-flood',
    node_id: 'a1b2c3d4-0003-4000-8000-000000000003',
    hazard_type: 'flood',
    severity: 'high',
    message: 'Critical water level: 3100/4095 — possible flooding.',
    resolved: false,
    created_at: hoursAgo(2),
  },
  {
    id: 'alert-sarobar-fire',
    node_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    hazard_type: 'fire',
    severity: 'high',
    message: 'Fire detected at node. Temp: 42.1°C, flame sensor active.',
    resolved: false,
    created_at: hoursAgo(5),
  },
  {
    id: 'alert-sundarbans-flood',
    node_id: 'a1b2c3d4-0001-4000-8000-000000000001',
    hazard_type: 'flood',
    severity: 'medium',
    message: 'Elevated water level: 2100/4095 — monitor closely.',
    resolved: false,
    created_at: hoursAgo(6),
  },
];

/** Alerts joined to their node and to the user's distance from it. */
export const ALERTS: AlertWithContext[] = RAW_ALERTS.map((alert) => {
  const node = nodeById(alert.node_id);
  return {
    ...alert,
    node,
    distanceMetres: distanceMetres(USER_POSITION, node),
    trigger: TRIGGER_READINGS[alert.id] ?? null,
  };
});

/**
 * Real places in and around Ward 58. Elevation matters more than distance in a
 * Kolkata flood — the city is almost flat, so a metre of ground floor height is
 * the difference between a dry shelter and a wet one.
 */
export const SHELTERS: Shelter[] = [
  {
    id: 'shelter-deshapriya',
    name: 'Deshapriya Park Community Hall',
    address: 'Deshapriya Park East, off Rash Behari Avenue',
    latitude: 22.5175,
    longitude: 88.3585,
    capacity: 400,
    occupancy: 186,
    status: 'open',
    elevationMetres: 7.5,
    facilities: ['Drinking water', 'Toilets', 'Medical desk', 'Phone charging'],
  },
  {
    id: 'shelter-lake-gardens',
    name: 'Lake Gardens Govt. High School',
    address: 'Lake Gardens, near the railway crossing',
    latitude: 22.506,
    longitude: 88.356,
    capacity: 250,
    occupancy: 244,
    status: 'full',
    elevationMetres: 6.5,
    facilities: ['Drinking water', 'Toilets'],
  },
  {
    id: 'shelter-netaji-indoor',
    name: 'Netaji Indoor Stadium',
    address: 'Eden Gardens, Strand Road',
    latitude: 22.5636,
    longitude: 88.3395,
    capacity: 2000,
    occupancy: 410,
    status: 'open',
    elevationMetres: 6.0,
    facilities: [
      'Drinking water',
      'Toilets',
      'Medical desk',
      'Cooked meals',
      'Family rooms',
    ],
  },
  {
    id: 'shelter-jadavpur',
    name: 'Jadavpur Vidyapith',
    address: 'Bijoygarh, off Raja S C Mallick Road',
    latitude: 22.499,
    longitude: 88.3695,
    capacity: 300,
    occupancy: 92,
    status: 'open',
    elevationMetres: 8.2,
    facilities: ['Drinking water', 'Toilets', 'Cooked meals'],
  },
];

// PLACEHOLDER_ZONES
