import { useCallback, useEffect, useMemo, useState } from 'react';
import { Download } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { severityWeight, SEVERITY_ORDER } from '../lib/severity';
import {
  Button, Chip, EmptyState, PageHeader, Panel,
} from '../components/panels';

/**
 * The alert log — every row a row in `alerts`, every column a column.
 *
 * This table used to carry a "confidence" percentage with a progress bar behind
 * it, generated by `Math.random()` on every fetch. The schema has no such field,
 * and a number an operator might act on cannot be decoration, so it is gone.
 * What the schema does have and this page was discarding is `message` — the
 * sentence the database trigger writes when a reading crosses a threshold. That
 * is the most useful thing in the row, so it is what the row now says.
 *
 * The filter and the export are wired to the same list you are looking at. They
 * were both dead buttons.
 */

const HAZARDS = ['flood', 'fire'];
const SEVERITIES = SEVERITY_ORDER;

function ageOf(iso) {
  const mins = Math.round((Date.now() - new Date(iso).getTime()) / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins} min ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs} h ago`;
  return `${Math.round(hrs / 24)} d ago`;
}

const stamp = (iso) => new Date(iso).toLocaleString([], {
  day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit',
});

/** RFC 4180 enough for a spreadsheet: quote everything, double the quotes. */
function toCsv(rows) {
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const head = ['raised_at', 'node', 'hazard', 'severity', 'status', 'message'];
  const body = rows.map((a) => [
    a.created_at, a.sensor_nodes?.name, a.hazard_type, a.severity,
    a.resolved ? 'resolved' : 'active', a.message,
  ].map(esc).join(','));
  return [head.join(','), ...body].join('\n');
}

function download(name, text) {
  const url = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

export default function AlertsLog() {
  const [alerts, setAlerts] = useState([]);
  const [state, setState] = useState(isSupabaseConfigured ? 'loading' : 'unconfigured');
  const [hazard, setHazard] = useState('all');
  const [severity, setSeverity] = useState('all');
  const [openOnly, setOpenOnly] = useState(false);

  const load = useCallback(async () => {
    const { data, error } = await supabase
      .from('alerts')
      .select('*, sensor_nodes(name)')
      .order('created_at', { ascending: false })
      .limit(200);
    if (error) {
      setState('error');
      return;
    }
    setAlerts(data || []);
    setState('ready');
  }, []);

  useEffect(() => {
    if (!isSupabaseConfigured) return undefined;
    load();

    const channel = supabase
      .channel('realtime-alerts-log')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'alerts' },
        // The node name lives on another table, and the payload only carries
        // `node_id`. Re-reading the joined row is cheaper than keeping a node
        // lookup in sync, and it means an UPDATE that resolves an alert lands
        // here too rather than leaving a stale "Active" on screen.
        () => { load(); },
      )
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [load]);

  const rows = useMemo(() => alerts.filter((a) => (
    (hazard === 'all' || a.hazard_type === hazard)
    && (severity === 'all' || a.severity === severity)
    && (!openOnly || !a.resolved)
  )), [alerts, hazard, severity, openOnly]);

  const open = alerts.filter((a) => !a.resolved).length;

  return (
    <div className="h-full overflow-y-auto bg-black p-6 text-white/80">
      <PageHeader
        title="Alert log"
        right={(
          <>
            <Button onClick={() => setOpenOnly((v) => !v)} active={openOnly}>
              Unresolved only
            </Button>
            <Button
              onClick={() => download(`alerts-${new Date().toISOString().slice(0, 10)}.csv`, toCsv(rows))}
              disabled={!rows.length}
              title={rows.length ? `Export ${rows.length} rows` : 'Nothing to export'}
            >
              <span className="flex items-center gap-1.5"><Download size={13} /> Export CSV</span>
            </Button>
          </>
        )}
      >
        Every alert the database has raised, newest first, up to 200. New rows and
        resolutions arrive over the live channel — nothing here is polled or padded.
      </PageHeader>

      <div className="mt-4 flex flex-wrap items-center gap-2">
        <span className="text-[11px] text-white/40">Hazard</span>
        <Button onClick={() => setHazard('all')} active={hazard === 'all'}>All</Button>
        {HAZARDS.map((h) => (
          <Button key={h} onClick={() => setHazard(h)} active={hazard === h}>
            {h[0].toUpperCase() + h.slice(1)}
          </Button>
        ))}
        <span className="ml-3 text-[11px] text-white/40">Severity</span>
        <Button onClick={() => setSeverity('all')} active={severity === 'all'}>All</Button>
        {SEVERITIES.map((s) => (
          <Button key={s} onClick={() => setSeverity(s)} active={severity === s}>
            {s[0].toUpperCase() + s.slice(1)}
          </Button>
        ))}
      </div>

      <Panel
        className="mt-4"
        bodyClass="p-0"
        title={`${rows.length} of ${alerts.length} shown`}
        right={state === 'ready' ? `${open} unresolved` : null}
      >
        {state === 'unconfigured' && (
          <EmptyState title="No database connection">
            Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY and reload. This page has
            no offline sample to show you — an invented alert log is worse than an
            empty one.
          </EmptyState>
        )}
        {state === 'loading' && <EmptyState title="Reading the alert table…" />}
        {state === 'error' && (
          <EmptyState title="The alert query failed">
            The table did not answer. Check the project URL, the anon key and the
            row-level-security policy on `alerts`.
          </EmptyState>
        )}
        {state === 'ready' && !alerts.length && (
          <EmptyState title="No alerts on record">
            The table is empty. Nothing has crossed a threshold since the sensors
            started reporting.
          </EmptyState>
        )}
        {state === 'ready' && alerts.length > 0 && !rows.length && (
          <EmptyState title="No alerts match this filter">
            {alerts.length} alerts are on record. Widen the hazard or severity filter.
          </EmptyState>
        )}

        {rows.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-[12px]">
              <thead className="border-b border-white/10 text-[11px] text-white/40">
                <tr>
                  <th className="px-4 py-2 font-medium">Raised</th>
                  <th className="px-4 py-2 font-medium">Node</th>
                  <th className="px-4 py-2 font-medium">Hazard</th>
                  <th className="px-4 py-2 font-medium">Severity</th>
                  <th className="px-4 py-2 font-medium">What the sensor reported</th>
                  <th className="px-4 py-2 text-right font-medium">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/[0.07]">
                {rows.map((a) => (
                  <tr key={a.id} className="align-top transition-colors hover:bg-white/[0.03]">
                    <td className="px-4 py-2.5 whitespace-nowrap tabular-nums text-white/75">
                      {stamp(a.created_at)}
                      <span className="block text-[10px] text-white/35">{ageOf(a.created_at)}</span>
                    </td>
                    <td className="px-4 py-2.5 text-white/85">
                      {a.sensor_nodes?.name || <span className="text-white/35">node deleted</span>}
                    </td>
                    <td className="px-4 py-2.5 text-white/60">{a.hazard_type}</td>
                    <td className="px-4 py-2.5">
                      <Chip weight={severityWeight(a.severity)}>{a.severity}</Chip>
                    </td>
                    <td className="max-w-md px-4 py-2.5 leading-relaxed text-white/70">
                      {a.message || <span className="text-white/30">no message recorded</span>}
                    </td>
                    <td className="px-4 py-2.5 text-right whitespace-nowrap">
                      {a.resolved
                        ? <span className="text-[11px] text-white/40">Resolved</span>
                        : <Chip weight={0.85}>Active</Chip>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </div>
  );
}
