-- ============================================================
-- BHOOMI-NETRA: Core Tables
-- Disaster monitoring sensor network for SIH 2026 (26178)
-- ============================================================

-- Sensor nodes deployed across Kolkata
CREATE TABLE sensor_nodes (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL,
  node_type   text NOT NULL CHECK (node_type IN ('forest', 'urban', 'universal')),
  latitude    float8 NOT NULL,
  longitude   float8 NOT NULL,
  location    geography(Point, 4326),
  status      text NOT NULL DEFAULT 'active',
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Telemetry readings from each node
CREATE TABLE readings (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id         uuid NOT NULL REFERENCES sensor_nodes(id) ON DELETE CASCADE,
  temperature     float4,
  humidity        float4,
  flame_detected  boolean,
  smoke_level     int4,
  water_level     int4,
  rain_level      int4,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Alerts generated by trigger logic or manual entry
CREATE TABLE alerts (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id     uuid NOT NULL REFERENCES sensor_nodes(id) ON DELETE CASCADE,
  hazard_type text NOT NULL CHECK (hazard_type IN ('flood', 'fire')),
  severity    text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  message     text,
  resolved    boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Performance indexes
CREATE INDEX idx_readings_node_id    ON readings(node_id);
CREATE INDEX idx_readings_created_at ON readings(created_at DESC);
CREATE INDEX idx_alerts_node_id      ON alerts(node_id);
CREATE INDEX idx_alerts_created_at   ON alerts(created_at DESC);
