-- ============================================================
-- Remove the public insert path on alerts
-- ============================================================
--
-- Applied 2026-09-06, on the go-ahead from the database owner, ahead of the
-- dashboard and citizen app going public. It was parked in supabase/proposed/
-- until then because it changes row level security.
--
-- ------------------------------------------------------------
-- Why this exists
-- ------------------------------------------------------------
-- The citizen mobile app ships the anon key inside its binary, and the web
-- dashboard ships it inside its JavaScript bundle. That is normal for Supabase —
-- anon keys are public by design and RLS is what protects the data — but it means
-- every policy granted to `anon` is effectively granted to anyone who downloads
-- the APK and runs `strings` on it, or opens devtools on the dashboard.
--
-- 003_rls_policies.sql granted:
--
--   CREATE POLICY "alerts_insert" ON alerts FOR INSERT WITH CHECK (true);
--
-- So anyone holding the anon key could insert a row into `alerts` with severity
-- 'critical'. In this app a critical alert for the user's zone triggers a
-- full-screen takeover and vibration that cannot be dismissed by scrolling. A
-- public insert policy on that table is a public "make every phone in Kolkata
-- scream" endpoint.
--
-- The policy is not needed. generate_alert_from_reading() in
-- 004_alert_trigger.sql is SECURITY DEFINER, so its INSERT runs as the function
-- owner and bypasses RLS regardless of what `anon` may do. Alerts keep being
-- generated from readings exactly as they were.
--
-- The ESP32 firmware is unaffected: it posts to `readings`, and
-- "readings_insert" stays as it is. Nothing else writes alerts — the web
-- dashboard only runs SELECT and realtime subscriptions against this table, and
-- the citizen app only reads it through PostgREST.
--
-- ------------------------------------------------------------
-- What this changes
-- ------------------------------------------------------------
-- Removes the public insert path on alerts. Authorities issuing a manual alert
-- do so through an authenticated dashboard session or the service role, which is
-- what the alerts table comment in 002_tables.sql already anticipated
-- ("generated by trigger logic or manual entry").

DROP POLICY IF EXISTS "alerts_insert" ON alerts;

-- Targets the Postgres role directly rather than testing auth.role() in the
-- body. Same outcome, but it does not depend on a helper that Supabase has moved
-- away from, and an unauthenticated request is rejected before the check runs.
CREATE POLICY "alerts_insert_authenticated" ON alerts
  FOR INSERT TO authenticated WITH CHECK (true);

-- Readings stay publicly insertable so the field hardware keeps working with the
-- anon key, per the contract in firmware/README.md. Known residual risk: a forged
-- reading above the flood threshold still reaches the trigger and produces a real
-- 'high' alert. Closing that means per-device credentials rather than a shared
-- anon key, which is a firmware change and not an RLS one.

